# Generated by Django 3.1.7 on 2021-03-17 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('acct_number', models.CharField(max_length=30)),
                ('name_on_acct', models.CharField(max_length=55)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('least_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Providers', related_query_name='Provider', to='healthybillsapi.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', related_query_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
